### PR TITLE
image upload has been fixed

### PR DESCRIPTION
**Pull request by EfazS04**
Image has been fixed. Finally done Tdot_Chaudry

### CODE REVIEW

**Comment by Taha-Chaudhry** [comment]
change gitignore so it doesnt use uploads

**Comment by Taha-Chaudhry** [comment]
otherwise we'll keep committing with new images from each product

**Comment by EfazS04** [comment]
Sure thing sir

**Comment by Taha-Chaudhry** [comment]
ai delete the images too jokeman

**Comment by Taha-Chaudhry** [comment]
there's like 20 uploads u done, just leave uploads folder with only one file

**Comment by Taha-Chaudhry** [comment]
cuz github doesnt allow empty files

**Comment by Taha-Chaudhry** [comment]
leave like default in there or sum

**Pull request merged**
